services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports: !override
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      NODE_ENV: development
      WATCHPACK_POLLING: "true"
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3000}
      APP_URL: ${APP_URL:-http://localhost:3000}
      MINIO_PUBLIC_URL: ${MINIO_PUBLIC_URL:-http://localhost:3000/api/storage}
      SMTP_CONSOLE: ${SMTP_CONSOLE:-true}

  mongodb:
    ports:
      - "27017:27017"

  minio:
    ports:
      - "9000:9000"
      - "9001:9001"

  mongo-express:
    ports: !override
      - "8081:8081"
